In [1]:
import numpy as np
import pandas as pd

In [2]:
data_preprocessed = pd.read_csv('Absenteeism_preprocessed.csv')
data_preprocessed.head(20)

Reason_1  Reason_2  Reason_3  Reason_4        Date  \
0          0         0         0         1  2015-07-07   
1          0         0         0         0  2015-07-14   
2          0         0         1         0  2015-07-15   
3          1         0         0         0  2015-07-16   
4          0         0         1         0  2015-07-23   
5          0         0         1         0  2015-07-10   
6          0         0         1         0  2015-07-17   
7          0         0         1         0  2015-07-24   
8          0         0         1         0  2015-07-06   
9          0         0         1         0  2015-07-13   
10         0         0         0         0  2015-07-20   
11         0         0         0         0  2015-07-14   
12         1         0         0         0  2015-07-15   
13         1         0         0         0  2015-07-15   
14         0         0         1         0  2015-07-15   
15         1         0         0         0  2015-07-17   
16         0         0         1         0  2015-07-17   
17         0         0         1         0  2015-07-27   
18         1         0         0         0  2015-07-30   
19         0         0         1         0  2015-08-05   

    Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                      289                36   33                  239.554   
1                      118                13   50                  239.554   
2                      179                51   38                  239.554   
3                      279                 5   39                  239.554   
4                      289                36   33                  239.554   
5                      179                51   38                  239.554   
6                      361                52   28                  239.554   
7                      260                50   36                  239.554   
8                      155                12   34                  239.554   
9                      235                11   37                  239.554   
10                     260                50   36                  239.554   
11                     260                50   36                  239.554   
12                     260                50   36                  239.554   
13                     179                51   38                  239.554   
14                     179                51   38                  239.554   
15                     246                25   41                  239.554   
16                     179                51   38                  239.554   
17                     179                51   38                  239.554   
18                     189                29   33                  239.554   
19                     248                25   47                  205.917   

    Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0                30          0         2     1                          4   
1                31          0         1     0                          0   
2                31          0         0     0                          2   
3                24          0         2     0                          4   
4                30          0         2     1                          2   
5                31          0         0     0                          2   
6                27          0         1     4                          8   
7                23          0         4     0                          4   
8                25          0         2     0                         40   
9                29          1         1     1                          8   
10               23          0         4     0                          8   
11               23          0         4     0                          8   
12               23          0         4     0                          8   
13               31          0         0     0                      

In [3]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [4]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 3, 1, 0)

In [5]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [6]:
data_preprocessed['Excessive Absenteeism'] = targets
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4        Date  Transportation Expense  \
0         0         0         0         1  2015-07-07                     289   
1         0         0         0         0  2015-07-14                     118   
2         0         0         1         0  2015-07-15                     179   
3         1         0         0         0  2015-07-16                     279   
4         0         0         1         0  2015-07-23                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   
3                 5   39                  239.554               24          0   
4                36   33                  239.554               30          0   

   Children  Pets  Absenteeism Time in Hours  Month Value  Day of the Week  \
0         2     1                          4            7                1   
1         1     0                          0            7                1   
2         0     0                          2            7                2   
3         2     0                          4            7                3   
4         2     1                          2            7                3   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [7]:
targets.sum() / targets.shape[0]


0.45571428571428574

In [8]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours', 'Date', 'Day of the Week',
                                            'Daily Work Load Average', 'Distance to Work'], axis=1)
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense  Age  \
0         0         0         0         1                     289   33   
1         0         0         0         0                     118   50   
2         0         0         1         0                     179   38   
3         1         0         0         0                     279   39   
4         0         0         1         0                     289   33   

   Body Mass Index  Education  Children  Pets  Month Value  \
0               30          0         2     1            7   
1               31          0         1     0            7   
2               31          0         0     0            7   
3               24          0         2     0            7   
4               30          0         2     1            7   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [9]:
data_with_targets.iloc[:,:-1]


Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense  Age  \
0           0         0         0         1                     289   33   
1           0         0         0         0                     118   50   
2           0         0         1         0                     179   38   
3           1         0         0         0                     279   39   
4           0         0         1         0                     289   33   
..        ...       ...       ...       ...                     ...  ...   
695         1         0         0         0                     179   40   
696         1         0         0         0                     225   28   
697         1         0         0         0                     330   28   
698         0         0         1         0                     235   32   
699         0         0         0         1                     291   40   

     Body Mass Index  Education  Children  Pets  Month Value  
0                 30          0         2     1            7  
1                 31          0         1     0            7  
2                 31          0         0     0            7  
3                 24          0         2     0            7  
4                 30          0         2     1            7  
..               ...        ...       ...   ...          ...  
695               22          1         2     0            5  
696               24          0         1     2            5  
697               25          1         0     0            5  
698               25          1         0     0            5  
699               25          0         1     1            5  

[700 rows x 11 columns]

In [10]:
unscaled_inputs = data_with_targets.iloc[:,:-1]

In [11]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator, TransformerMixin):
    def __init__(self, columns, copy=True, with_mean=True, with_std=True):
        self.scaler = StandardScaler(copy, with_mean, with_std)
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns],y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        X_not_scaled = X.loc[:, ~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [12]:
data_with_targets.shape

(700, 12)

In [13]:
data_with_targets.iloc[:,:-1]


Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense  Age  \
0           0         0         0         1                     289   33   
1           0         0         0         0                     118   50   
2           0         0         1         0                     179   38   
3           1         0         0         0                     279   39   
4           0         0         1         0                     289   33   
..        ...       ...       ...       ...                     ...  ...   
695         1         0         0         0                     179   40   
696         1         0         0         0                     225   28   
697         1         0         0         0                     330   28   
698         0         0         1         0                     235   32   
699         0         0         0         1                     291   40   

     Body Mass Index  Education  Children  Pets  Month Value  
0                 30          0         2     1            7  
1                 31          0         1     0            7  
2                 31          0         0     0            7  
3                 24          0         2     0            7  
4                 30          0         2     1            7  
..               ...        ...       ...   ...          ...  
695               22          1         2     0            5  
696               24          0         1     2            5  
697               25          1         0     0            5  
698               25          1         0     0            5  
699               25          0         1     1            5  

[700 rows x 11 columns]

In [14]:
unscaled_inputs = data_with_targets.iloc[:,:-1]


In [15]:
#from sklearn.preprocessing import StandardScaler

#absenteeism_scaler = StandardScaler()

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator, TransformerMixin):
    def __init__(self, columns, copy=True, with_mean=True, with_std=True):
        self.scaler = StandardScaler(copy, with_mean, with_std)
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns],y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        X_not_scaled = X.loc[:, ~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [16]:
unscaled_inputs.columns.values


array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Month Value'], dtype=object)

In [17]:
columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Education']
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [18]:
absenteeism_scaler = CustomScaler(columns_to_scale)

C:\Users\Admin\Miniconda3\lib\site-packages\sklearn\utils\validation.py:70: FutureWarning: Pass copy=True, with_mean=True, with_std=True as keyword args. From version 0.25 passing these as positional arguments will result in an error
  FutureWarning)


In [19]:
absenteeism_scaler.fit(unscaled_inputs)

C:\Users\Admin\Miniconda3\lib\site-packages\sklearn\base.py:213: FutureWarning: From version 0.24, get_params will raise an AttributeError if a parameter cannot be retrieved as an instance attribute. Previously it would return None.
  FutureWarning)


CustomScaler(columns=['Transportation Expense', 'Age', 'Body Mass Index',
                      'Children', 'Pets', 'Month Value'],
             copy=None, with_mean=None, with_std=None)

In [20]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)
scaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense       Age  \
0           0         0         0         1                1.005844 -0.536062   
1           0         0         0         0               -1.574681  2.130803   
2           0         0         1         0               -0.654143  0.248310   
3           1         0         0         0                0.854936  0.405184   
4           0         0         1         0                1.005844 -0.536062   
..        ...       ...       ...       ...                     ...       ...   
695         1         0         0         0               -0.654143  0.562059   
696         1         0         0         0                0.040034 -1.320435   
697         1         0         0         0                1.624567 -1.320435   
698         0         0         1         0                0.190942 -0.692937   
699         0         0         0         1                1.036026  0.562059   

     Body Mass Index  Education  Children      Pets  Month Value  
0           0.767431          0  0.880469  0.268487     0.182726  
1           1.002633          0 -0.019280 -0.589690     0.182726  
2           1.002633          0 -0.919030 -0.589690     0.182726  
3          -0.643782          0  0.880469 -0.589690     0.182726  
4           0.767431          0  0.880469  0.268487     0.182726  
..               ...        ...       ...       ...          ...  
695        -1.114186          1  0.880469 -0.589690    -0.388293  
696        -0.643782          0 -0.019280  1.126663    -0.388293  
697        -0.408580          1 -0.919030 -0.589690    -0.388293  
698        -0.408580          1 -0.919030 -0.589690    -0.388293  
699        -0.408580          0 -0.019280  0.268487    -0.388293  

[700 rows x 11 columns]

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
train_test_split(scaled_inputs,targets)

[     Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense       Age  \
 541         0         0         0         1                1.036026  0.562059   
 34          0         0         1         0               -0.654143  0.248310   
 16          0         0         1         0               -0.654143  0.248310   
 41          0         0         1         0               -1.574681  0.091435   
 55          0         0         0         0               -1.574681  2.130803   
 ..        ...       ...       ...       ...                     ...       ...   
 335         1         0         0         0                0.568211 -0.065439   
 509         0         0         0         1                0.356940  0.718933   
 298         0         0         0         1               -0.654143  0.248310   
 405         0         0         0         0                0.190942  0.091435   
 658         1         0         0         0               -0.503235 -0.536062   
 
      Body Mas

In [23]:
x_train,x_test,y_train,y_test=train_test_split(scaled_inputs,targets,train_size=0.8,random_state=20)

In [24]:
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(560, 11) (140, 11) (560,) (140,)


In [25]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [26]:
reg = LogisticRegression()
reg.fit(x_train, y_train)

LogisticRegression()

In [27]:
reg.score(x_train, y_train)

0.7089285714285715

In [28]:
model_outputs = reg.predict(x_train)
model_outputs

array([0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0,

In [29]:
model_outputs==y_train

array([ True, False, False, False,  True,  True, False,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False, False,  True,  True,
       False,  True, False,  True,  True,  True,  True,  True,  True,
        True, False,  True, False,  True, False, False,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True, False, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True, False,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True, False, False,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,

In [30]:
np.sum(model_outputs==y_train)

397

In [31]:
model_outputs.shape[0]

560

In [32]:
np.sum((model_outputs==y_train))/model_outputs.shape[0]

0.7089285714285715

In [33]:
reg.intercept_

array([-0.74133437])

In [34]:
reg.coef_

array([[ 1.72449218,  1.50670926,  0.40211338, -0.08564521,  0.56313201,
        -0.13296701,  0.22654884, -0.03728443,  0.32386935, -0.27278374,
         0.11586695]])

In [35]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Month Value'], dtype=object)

In [36]:
feature_names=unscaled_inputs.columns.values

In [37]:
summary_table = pd.DataFrame(columns=['Feature name'], data = feature_names)
summary_table['Coefficient'] = np.transpose(reg.coef_)
summary_table

Feature name  Coefficient
0                 Reason_1     1.724492
1                 Reason_2     1.506709
2                 Reason_3     0.402113
3                 Reason_4    -0.085645
4   Transportation Expense     0.563132
5                      Age    -0.132967
6          Body Mass Index     0.226549
7                Education    -0.037284
8                 Children     0.323869
9                     Pets    -0.272784
10             Month Value     0.115867

In [38]:
summary_table.index = summary_table.index+1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature name  Coefficient
0                Intercept    -0.741334
1                 Reason_1     1.724492
2                 Reason_2     1.506709
3                 Reason_3     0.402113
4                 Reason_4    -0.085645
5   Transportation Expense     0.563132
6                      Age    -0.132967
7          Body Mass Index     0.226549
8                Education    -0.037284
9                 Children     0.323869
10                    Pets    -0.272784
11             Month Value     0.115867

In [39]:
summary_table['Odds Ratio'] = np.exp(summary_table.Coefficient)
summary_table

Feature name  Coefficient  Odds Ratio
0                Intercept    -0.741334    0.476478
1                 Reason_1     1.724492    5.609672
2                 Reason_2     1.506709    4.511859
3                 Reason_3     0.402113    1.494981
4                 Reason_4    -0.085645    0.917920
5   Transportation Expense     0.563132    1.756164
6                      Age    -0.132967    0.875494
7          Body Mass Index     0.226549    1.254264
8                Education    -0.037284    0.963402
9                 Children     0.323869    1.382467
10                    Pets    -0.272784    0.761257
11             Month Value     0.115867    1.122846

In [40]:
summary_table.sort_values('Odds Ratio', ascending=False)

Feature name  Coefficient  Odds Ratio
1                 Reason_1     1.724492    5.609672
2                 Reason_2     1.506709    4.511859
5   Transportation Expense     0.563132    1.756164
3                 Reason_3     0.402113    1.494981
9                 Children     0.323869    1.382467
7          Body Mass Index     0.226549    1.254264
11             Month Value     0.115867    1.122846
8                Education    -0.037284    0.963402
4                 Reason_4    -0.085645    0.917920
6                      Age    -0.132967    0.875494
10                    Pets    -0.272784    0.761257
0                Intercept    -0.741334    0.476478

In [41]:
reg.score(x_test, y_test)

0.6642857142857143

In [42]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.7280024 , 0.2719976 ],
       [0.59941005, 0.40058995],
       [0.48713231, 0.51286769],
       [0.77715449, 0.22284551],
       [0.39216962, 0.60783038],
       [0.36332144, 0.63667856],
       [0.33682416, 0.66317584],
       [0.481931  , 0.518069  ],
       [0.77998927, 0.22001073],
       [0.65228019, 0.34771981],
       [0.41721711, 0.58278289],
       [0.16983051, 0.83016949],
       [0.32276992, 0.67723008],
       [0.58690804, 0.41309196],
       [0.43101182, 0.56898818],
       [0.52030555, 0.47969445],
       [0.45789938, 0.54210062],
       [0.4496999 , 0.5503001 ],
       [0.39428281, 0.60571719],
       [0.29508008, 0.70491992],
       [0.60993371, 0.39006629],
       [0.77715449, 0.22284551],
       [0.45803732, 0.54196268],
       [0.45803732, 0.54196268],
       [0.66342655, 0.33657345],
       [0.7502972 , 0.2497028 ],
       [0.39898799, 0.60101201],
       [0.74511834, 0.25488166],
       [0.62169586, 0.37830414],
       [0.77715449, 0.22284551],
       [0.

In [43]:
predicted_proba[:,1]

array([0.2719976 , 0.40058995, 0.51286769, 0.22284551, 0.60783038,
       0.63667856, 0.66317584, 0.518069  , 0.22001073, 0.34771981,
       0.58278289, 0.83016949, 0.67723008, 0.41309196, 0.56898818,
       0.47969445, 0.54210062, 0.5503001 , 0.60571719, 0.70491992,
       0.39006629, 0.22284551, 0.54196268, 0.54196268, 0.33657345,
       0.2497028 , 0.60101201, 0.25488166, 0.37830414, 0.22284551,
       0.48810883, 0.64809953, 0.65184052, 0.59877663, 0.22284551,
       0.63181841, 0.2257402 , 0.60338934, 0.39760578, 0.69853151,
       0.2171689 , 0.49624651, 0.2375135 , 0.60783038, 0.78518082,
       0.42209337, 0.66897501, 0.37830414, 0.23710038, 0.21159752,
       0.58634561, 0.55871448, 0.63667856, 0.27484943, 0.80331285,
       0.53765689, 0.53387826, 0.24238174, 0.51773381, 0.5259881 ,
       0.70499428, 0.62899221, 0.39643563, 0.6436863 , 0.3078254 ,
       0.36287329, 0.19611794, 0.32196325, 0.33606397, 0.44549909,
       0.2257402 , 0.5138586 , 0.86929057, 0.55915006, 0.56236

In [44]:
import pickle

In [45]:
with open('model', 'wb') as file:
    pickle.dump(reg, file)

In [46]:
with open('scaler', 'wb') as file:
    pickle.dump(absenteeism_scaler, file)